export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";

export const SEARCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const SEARCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const SEARCH_POST_FAILURE = "FETCH_POST_FAILURE";
